server:
  port: 9091
  servlet:
    context-path: /

springdoc:
  packagesToScan: org.darozhka.parceldelivery.delivery.rest
  swagger-ui:
    docExpansion: none
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: alpha

spring:
  main:
    allow-circular-references: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db-migration/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5444/parcel_delivery
    username: parcel_delivery
    password: parcel_delivery
    hikari:
      maximum-pool-size: 15
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://guavapay-auth-server:9090
      client:
        registration:
          delivery-service:
            provider: delivery-service
            client-id: parcel_delivery
            client-secret: parcel_delivery
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9091/login/oauth2/code/delivery-service"
            scope: openid,delivery
        provider:
          delivery-service:
            issuer-uri: http://guavapay-auth-server:9090

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE

parceldelivery:
  kafka:
    bootstrap-address: localhost:9092
    topicName: "parceldelivery"
    consumerGroupId: "delivery-service"